name: Deploy to CPanel via FTP

on:
  push:
    branches:
      - feat/master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Langkah Baru: Setup PHP ---
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # Sesuaikan dengan kebutuhan minimal project Anda
          extensions: mbstring, xml, ctype, iconv, mysql, zip
          coverage: none

      # --- Langkah Baru: Install Composer Dependencies ---
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --ignore-platform-reqs

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy to CPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: / # sesuaikan root hosting
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.env
            **/node_modules/**
            **/storage/**
            **/tests/**
